-- Phase 1: preparation. Keeps existing customer pages and template rows intact.
ALTER TABLE public.proxolink_cards ADD COLUMN IF NOT EXISTS page_type text NOT NULL DEFAULT 'contact';
ALTER TABLE public.proxolink_cards ADD CONSTRAINT proxolink_page_type_check CHECK(page_type IN ('contact','food','download'));
ALTER TABLE public.proxolink_templates DROP CONSTRAINT proxolink_templates_template_key_check;
ALTER TABLE public.proxolink_templates ADD CONSTRAINT proxolink_templates_template_key_check CHECK(template_key IN ('dark','light','classic','pill','card','neon','zoom','banner','pill-mint','pill-dark','pill-white'));
ALTER TABLE public.pa_contact_events DROP CONSTRAINT pa_contact_events_button_type_check;
ALTER TABLE public.pa_contact_events ADD CONSTRAINT pa_contact_events_button_type_check CHECK(button_type IS NULL OR button_type IN ('whatsapp','viber','telegram','instagram','phone','email','website','tiktok','talabat','lezzoo','toters','wade','app_store','google_play'));
INSERT INTO public.proxolink_templates(template_key,version,display_name_ckb,display_name_en,storage_path,checksum_sha256,requires_avatar,is_active,is_catalog_visible,renderer_variant,renderer_options) VALUES('pill',2,'پیل','Pill','pill/v2/template.html','8cc5f3e4dcc5559819bcb65d7e67db2ab0eb0bcf0b2d143f0f0dba992d0d70ec',false,true,true,'standard','{}'::jsonb) ON CONFLICT(template_key,version) DO UPDATE SET checksum_sha256=EXCLUDED.checksum_sha256,display_name_ckb=EXCLUDED.display_name_ckb,display_name_en=EXCLUDED.display_name_en,requires_avatar=false,is_active=true,is_catalog_visible=true,storage_path=EXCLUDED.storage_path,renderer_variant='standard',renderer_options='{}'::jsonb;
INSERT INTO public.proxolink_templates(template_key,version,display_name_ckb,display_name_en,storage_path,checksum_sha256,requires_avatar,is_active,is_catalog_visible,renderer_variant,renderer_options) VALUES('pill-mint',2,'پیل مینت','Pill Mint','pill-mint/v2/template.html','d6504909a13570ee57638096b0974f0f56e00181088ef718a69cb87159902f2b',false,true,true,'standard','{}'::jsonb) ON CONFLICT(template_key,version) DO UPDATE SET checksum_sha256=EXCLUDED.checksum_sha256,display_name_ckb=EXCLUDED.display_name_ckb,display_name_en=EXCLUDED.display_name_en,requires_avatar=false,is_active=true,is_catalog_visible=true,storage_path=EXCLUDED.storage_path,renderer_variant='standard',renderer_options='{}'::jsonb;
INSERT INTO public.proxolink_templates(template_key,version,display_name_ckb,display_name_en,storage_path,checksum_sha256,requires_avatar,is_active,is_catalog_visible,renderer_variant,renderer_options) VALUES('pill-dark',2,'پیل تاریک','Pill Dark','pill-dark/v2/template.html','44560c5e8e3b6e355a1f86cb23e45b672986267911afa4fa12ed21646e9cb943',false,true,true,'standard','{}'::jsonb) ON CONFLICT(template_key,version) DO UPDATE SET checksum_sha256=EXCLUDED.checksum_sha256,display_name_ckb=EXCLUDED.display_name_ckb,display_name_en=EXCLUDED.display_name_en,requires_avatar=false,is_active=true,is_catalog_visible=true,storage_path=EXCLUDED.storage_path,renderer_variant='standard',renderer_options='{}'::jsonb;
INSERT INTO public.proxolink_templates(template_key,version,display_name_ckb,display_name_en,storage_path,checksum_sha256,requires_avatar,is_active,is_catalog_visible,renderer_variant,renderer_options) VALUES('pill-white',2,'پیل سپی','Pill White','pill-white/v2/template.html','e267008a4ecb2b97d4e3ea597bb7bf78a94629ee9d229754c7f97388d0e26251',false,true,true,'standard','{}'::jsonb) ON CONFLICT(template_key,version) DO UPDATE SET checksum_sha256=EXCLUDED.checksum_sha256,display_name_ckb=EXCLUDED.display_name_ckb,display_name_en=EXCLUDED.display_name_en,requires_avatar=false,is_active=true,is_catalog_visible=true,storage_path=EXCLUDED.storage_path,renderer_variant='standard',renderer_options='{}'::jsonb;
